in this pull request, has the following;
Careen1234/PROJECTDO pull request #1
Opened 2024-08-09 10:28 UTC by Careen1234

- [ ] Creating a home page

2024-08-12 06:03 UTC, FilbertKimasa requested changes
Hello @Careen1234  😃,

Rquest changes
Great work and effort you put into this project so far.

 ## Required Changes ♻️
_Please check the comments under the review._

There are changes you need to make for your project to match the provided design. The following is the preview of your project 
![Screenshot from 2024-08-12 08-55-44](https://github.com/user-attachments/assets/5b92876e-34de-4351-b6e6-000d9a6b580b)

![Screenshot from 2024-08-12 08-52-50](https://github.com/user-attachments/assets/eeaccd37-5f7b-4dc4-a65c-7cb27dd6396d)

2024-08-12 06:03 UTC, FilbertKimasa commented on index.html
Please consider to write your styles in a separate CSS file

2024-08-13 08:27 UTC, Careen1234 commented
I  TRIED MAKING SOME BETTER  CHANGES PLEASE  CHECK

On Mon, Aug 12, 2024 at 9:04 AM Filbert Daniel ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hello @Careen1234 <https://github.com/Careen1234> 😃,
>
> Rquest changes
> Great work and effort you put into this project so far.
> Required Changes ♻️
>
> *Please check the comments under the review.*
>
> There are changes you need to make for your project to match the provided
> design. The following is the preview of your project
> Screenshot.from.2024-08-12.08-55-44.png (view on web)
> <https://github.com/user-attachments/assets/5b92876e-34de-4351-b6e6-000d9a6b580b>
>
> Screenshot.from.2024-08-12.08-52-50.png (view on web)
> <https://github.com/user-attachments/assets/eeaccd37-5f7b-4dc4-a65c-7cb27dd6396d>
> ------------------------------
>
> On index.html
> <https://github.com/Careen1234/PROJECTDO/pull/1#discussion_r1713194555>:
>
> Please consider to write your styles in a separate CSS file
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Careen1234/PROJECTDO/pull/1#pullrequestreview-2232085333>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7ZQ7XUZVKINS7CU7TIS5A3ZRBF5VAVCNFSM6AAAAABMIGMBFSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMZSGA4DKMZTGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-14 04:46 UTC, FilbertKimasa commented on index.css
> -header{
header selector is not closed, please make sure to all your selectors in your CSS

2024-08-14 04:48 UTC, FilbertKimasa commented on index.css
> +
Consider not to leave an empty space inside your selector, kindly remove all of them

2024-08-14 04:51 UTC, FilbertKimasa commented on index.html
> +            <img src="c:\Users\kalyst\Downloads\Microverse-Student-Project-1 (1)\Bars\Status Bars\Dark.png">
To deal with images in your project I advise to Crete a separate folder, for the images inside your project so that your project to be organized.

2024-08-14 04:56 UTC, FilbertKimasa commented on index.html
> -                    <img src="/home/codecraft/Downloads/Microverse-Student-Project-1/Linkdin icon.svg", alt="Linkdin">
Please add icons and images you used to a folder in your project, for good organization of your project. those images and icons for your project should also be present in the project repository in the git-hub.

2024-08-14 04:58 UTC, FilbertKimasa commented on index.html
> +
Too-much unused white space

2024-08-14 05:09 UTC, FilbertKimasa commented on index.css
> + width: Hug (375px)px;
consider using % for the width dimensions

2024-08-14 05:10 UTC, FilbertKimasa commented on index.css
> + width: Hug(375)px;
consider using % for the width dimensions of your layouts, for your project to be responsive

2024-08-14 05:10 UTC, FilbertKimasa commented on index.css
> +width: 375px;
consider using % for the width dimensions of your layouts, for your project to be responsive

2024-08-14 05:17 UTC, FilbertKimasa reviewed
## Hi :raising_hand: :raising_hand: @Careen1234 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
The nav bar is not as in the provided design and all of your images and icons are not visible. please fix that and read comments under the review.

<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

your design vs provided design
![Screenshot from 2024-08-14 08-12-12](https://github.com/user-attachments/assets/ed4db4f9-ae56-4836-8e1f-6072010d96f2)
![Screenshot from 2024-08-12 08-52-50](https://github.com/user-attachments/assets/2eaf1bcc-89e2-45d1-8f65-e0fef59f31b9)

2024-08-14 08:33 UTC, Careen1234 commented
ok😄

On Wed, Aug 14, 2024 at 7:48 AM Filbert Daniel ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In index.css
> <https://github.com/Careen1234/PROJECTDO/pull/1#discussion_r1716305195>:
>
> > @@ -1,6 +1,100 @@
> -header{
> -    background-color: #3C3A39;
> +.content{
> +background: #3C3A39;
> + width: Hug(375)px;
> +height: Hug(44)px;
> +gap: 0px;
> +opacity: 0px;
> +
>
> Consider not to leave an empty space inside your selector, kindly remove
> all of them
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Careen1234/PROJECTDO/pull/1#pullrequestreview-2237162796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7ZQ7XXX5TCG6GG7O5GGZTLZRLOSXAVCNFSM6AAAAABMIGMBFSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMZXGE3DENZZGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-15 05:48 UTC, Careen1234 commented on index.css
> +margin-right: 50%;
That margin-right makes your project unresponsive, please fix that

2024-08-15 05:53 UTC, FilbertKimasa requested changes
Hi @Careen1234 , good job so far, there are small changes to make for your project to match the provided design. please check the comments under the review

2024-08-16 04:45 UTC, FilbertKimasa approved these changes
Hi @Careen1234, your project is complete. You can merge it

2024-08-16 04:47 UTC, merged